/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CuentaBanco;

import org.junit.jupiter.api.*;
//import static org.junit.Assert.*;

public class LibraryTest {
  @Test 
  public void testSomeLibraryMethod() {
      Library classUnderTest = new Library();
      Assertions.assertTrue(classUnderTest.someLibraryMethod());
//      assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
  }
}
